const paths = {
  login: "login",
  forgotPassword: "forgot-password",
  verifyCode: "verify-code",
  resetPassword: "reset-password",
  profile: "profile",
  admin: "admin",
  home: "home",
  vendors: "vendors",
  customers: "customers",
  products: "products",
  purchaseOrders: "purchase-orders",
  salesOrders: "sales-orders",
  expenses: "expenses",
  warehouses: "warehouses",
  transfers: "transfers",
  reports: "reports",
  cash: "cash",
  payments: "payments",
  currencies: "currencies",
  categories: "categories",
  coupons: "coupons",
  customization: "customization",
  governorates: "governorates",
  transactions: "transactions",
  users: "users",
  analytics: "analytics",
  new: "new",
  update: "update",
  inventoryTransfer: "inventory-transfer",
  inventorySummary: "inventory-summary",
  variantHistory: "variant-history",
  treasuryBalance: "treasury-balance",
  profitBySales: "profit-by-sales",
  profitByCustomer: "profit-by-customer",
  profitByProduct: "profit-by-product",
  returns: "returns",
  fixedAssets: "fixed-assets",
  projects: "projects",
  accounts: "accounts",
  journalEntries: "journal-entries",
  incomeStatement: "income-statement",
  balanceSheet: "balance-sheet",
};

export default paths;
