import {
  HiOutlineUser,
  HiOutlineTrash,
  HiOutlineShoppingBag,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineUserCircle,
  HiOutlineArrowUpOnSquare,
  HiOutlineArrowDownOnSquare,
  HiOutlinePhoto,
  HiOutlineChartBar,
  HiOutlineComputerDesktop,
  HiOutlineShoppingCart,
  HiOutlineSquares2X2,
  HiOutlineUsers,
  HiArrowLeft,
  HiArrowRight,
  HiXMark,
  HiBars3,
  HiBars2,
  HiArrowsRightLeft,
  HiOutlineTicket,
  HiTicket,
  HiOutlineHome,
  HiOutlineCurrencyDollar,
  HiOutlineExclamationCircle,
  HiOutlineDocumentText,
} from "react-icons/hi2";
import {
  FaCircleExclamation,
  FaCircleCheck,
  FaCalendarDays,
  FaPercent,
  FaAngleDown,
  FaAngleUp,
  FaHashtag,
  FaTag,
  FaCircleXmark,
  FaDollarSign,
  FaRegEye,
  FaPhone,
  FaMap,
  FaRoad,
  FaHeart,
  FaFacebook,
  FaInstagram,
  FaTiktok,
  FaTwitter,
  FaWhatsapp,
  FaCheck,
  FaReceipt,
  FaBarcode,
  FaBuilding,
  FaRegBuilding,
  FaRegCircle,
} from "react-icons/fa6";
import { FaBox, FaArrowUp, FaArrowDown, FaChartBar, FaMapMarkedAlt, FaCircle, FaMoneyBillWave } from "react-icons/fa";
import {
  FiArrowUpCircle,
  FiArrowDownCircle,
  FiExternalLink,
  FiClock,
  FiCheckCircle,
  FiXCircle,
  FiPlus,
  FiMinus,
  FiBox,
} from "react-icons/fi";
import {
  IoGlobeSharp,
  IoHeartOutline,
  IoShirtOutline,
  IoFilter,
  IoCopyOutline,
  IoPrintOutline,
  IoDocumentText,
  IoReturnDownBackOutline,
} from "react-icons/io5";
import { IoIosSearch, IoMdPin, IoMdShare, IoIosBarcode } from "react-icons/io";
import { RiAdminLine, RiDiscountPercentLine, RiGovernmentFill } from "react-icons/ri";
import { MdLockOutline, MdOutlineSort, MdDoNotDisturb, MdOutlineFullscreen, MdDownload } from "react-icons/md";
import { TfiLayoutGrid2Alt, TfiLayoutGrid3Alt } from "react-icons/tfi";
import { LiaShippingFastSolid } from "react-icons/lia";
import { TbEdit, TbMenu } from "react-icons/tb";
import { CiMenuKebab } from "react-icons/ci";
import { ImSpinner8 } from "react-icons/im";
import { AiOutlineZoomIn, AiOutlineZoomOut } from "react-icons/ai";
import { PiOfficeChair } from "react-icons/pi";
import { GrAnalytics } from "react-icons/gr";
import { GiClothes, GiRolledCloth } from "react-icons/gi";
import { HiMiniArrowPath } from "react-icons/hi2";
import { GoShieldCheck } from "react-icons/go";

// ====================== ICONS ======================

export const outlineIcons = {
  User: HiOutlineUser,
  Admin: RiAdminLine,
  Globe: IoGlobeSharp,
  UserCircle: HiOutlineUserCircle,
  CheckCircle: FiCheckCircle,
  XMarkCircle: FiXCircle,
  ExclamationCircle: HiOutlineExclamationCircle,
  ArrowUpCircle: FiArrowUpCircle,
  ArrowDownCircle: FiArrowDownCircle,
  ArrowUpOnSquare: HiOutlineArrowUpOnSquare,
  ArrowDownOnSquare: HiOutlineArrowDownOnSquare,
  Clock: FiClock,
  Lock: MdLockOutline,
  Heart: IoHeartOutline,
  ShoppingBag: HiOutlineShoppingBag,
  ShoppingCart: HiOutlineShoppingCart,
  Shirt: IoShirtOutline,
  Edit: TbEdit,
  Trash: HiOutlineTrash,
  Photo: HiOutlinePhoto,
  Document: HiOutlineDocumentText,
  ChartBar: HiOutlineChartBar,
  Computer: HiOutlineComputerDesktop,
  Squares: HiOutlineSquares2X2,
  Users: HiOutlineUsers,
  Coupon: HiOutlineTicket,
  Shipping: LiaShippingFastSolid,
  Transaction: HiArrowsRightLeft,
  Discount: RiDiscountPercentLine,
  Copy: IoCopyOutline,
  Home: HiOutlineHome,
  Print: IoPrintOutline,
  DollarSign: HiOutlineCurrencyDollar,
  Building: FaRegBuilding,
  ZoomIn: AiOutlineZoomIn,
  ZoomOut: AiOutlineZoomOut,
  Fullscreen: MdOutlineFullscreen,
  Analytics: GrAnalytics,
  FixedAssets: PiOfficeChair,
  Box: FiBox,
  Circle: FaRegCircle,
  ShieldCheck: GoShieldCheck,
  Projects: FaBuilding,
  Accounts: IoDocumentText,
  JournalEntries: FaReceipt,
};

export const solidIcons = {
  Spinner: ImSpinner8,
  XMark: HiXMark,
  MenuKebab: CiMenuKebab,
  TbMenu: TbMenu,
  Bars3: HiBars3,
  Bars2: HiBars2,
  Plus: FiPlus,
  Minus: FiMinus,
  Check: FaCheck,
  Filter: IoFilter,
  Eye: FaRegEye,
  Heart: FaHeart,
  Hashtag: FaHashtag,
  Tag: FaTag,
  Box: FaBox,
  Analytics: FaChartBar,
  ArrowUp: FaArrowUp,
  ArrowDown: FaArrowDown,
  ArrowLeft: HiArrowLeft,
  ArrowRight: HiArrowRight,
  AngleUp: FaAngleUp,
  AngleDown: FaAngleDown,
  Search: IoIosSearch,
  Percent: FaPercent,
  DollarSign: FaDollarSign,
  Calendar: FaCalendarDays,
  Coupon: HiTicket,
  Circle: FaCircle,
  CheckCircle: FaCircleCheck,
  XmarkCircle: FaCircleXmark,
  ExclamationCircle: FaCircleExclamation,
  Adjustments: HiOutlineAdjustmentsHorizontal,
  MapMarked: FaMapMarkedAlt,
  Phone: FaPhone,
  Map: FaMap,
  Road: FaRoad,
  Government: RiGovernmentFill,
  Pin: IoMdPin,
  ExternalLink: FiExternalLink,
  Facebook: FaFacebook,
  Instagram: FaInstagram,
  Tiktok: FaTiktok,
  Twitter: FaTwitter,
  Whatsapp: FaWhatsapp,
  Share: IoMdShare,
  Sort: MdOutlineSort,
  LayoutGrid2: TfiLayoutGrid2Alt,
  LayoutGrid3: TfiLayoutGrid3Alt,
  NoSymbol: MdDoNotDisturb,
  Invoice: IoDocumentText,
  Receipt: FaReceipt,
  Barcode: FaBarcode,
  BarcodeScan: IoIosBarcode,
  Building: FaBuilding,
  Download: MdDownload,
  Return: IoReturnDownBackOutline,
  Clothes: GiClothes,
  RolledCloth: GiRolledCloth,
  ArrowPath: HiMiniArrowPath,
  Money: FaMoneyBillWave,
};
