const colors = [
  // Basic colors
  'black',
  'white',
  'red',
  'green',
  'blue',
  'yellow',
  'orange',
  'purple',
  'pink',
  'brown',
  'gray',
  'grey', // Alternative spelling
  'beige',
  'gold',
  'silver',
  'navy',
  'olive',
  'maroon',
  'teal',
  'khaki',
  'cream',

  // Additional colors from colorMapping.js
  'coffee',
  'offwhite',
  'off white',
  'purpple', // Alternative spelling
  'coffe', // Alternative spelling
  'grren', // Alternative spelling
  'full',
  'cafe au lait',
  'full cover',

  // Colors from import validation errors
  'baje', // Alternative spelling of beige
  'bej', // Alternative spelling of beige
  'burgandy', // Alternative spelling of burgundy
  'navy blue', // Compound color
  'baby blue', // Compound color
  'browne', // Alternative spelling of brown
  'olive green', // Compound color
  'petrol', // New color

  // Additional common colors
  'turquoise',
  'magenta',
  'cyan',
  'lime',
  'indigo',
  'violet',
  'coral',
  'salmon',
  'mint',
  'lavender',
  'plum',
  'peach',
  'tan',
  'aqua',
  'burgundy',
  'charcoal',
  'mustard',
  'emerald',
  'ruby',
  'sapphire',
  'amber',
  'ivory',
  'chocolate',
  'slate',
  'camel',
  'mauve',
  'taupe',
  'periwinkle',
  'crimson',
  'azure',
  'lilac',
  'sage',
  'rust',
  'cobalt',
  'fuchsia',
  'scarlet',
  'sienna',
  'terracotta',
  'champagne',
  'rose gold',
  'pewter',
  'bronze',
  'copper',
  'steel',
  'titanium',
  'graphite',
  'ash',
  'stone',
  'smoke',
  'ebony',
  'jet',
  'onyx',
  'pearl',
  'eggshell',
  'linen',
  'bone',
  'light blue',
  'dark blue',
  'light green',
  'dark green',
  'light red',
  'dark red',
  'light yellow',
  'dark yellow',
  'light orange',
  'dark orange',
  'light purple',
  'dark purple',
  'light pink',
  'dark pink',
  'light brown',
  'dark brown',
  'light gray',
  'dark gray',
  'light grey',
  'dark grey',
];

module.exports = colors;
